package ma.pharmachain.dto;

import lombok.Data;

@Data
public class TransferCreateRequest {
    private String toDriverCode;
    private String reason;
    private String transferBarcode; // Generated by mobile app
}

